#!/usr/bin/env python3
"""TEST ONLY: build the reference Interzone from Valley's own module code.

    python3 test/make_ref.py build/ref/interzone_ref.cc

Copies `struct Interzone : Module {...}` out of the vendored Interzone.hpp and the module's functions (constructor,
process, getParams, getCV, tickSynth, onSampleRateChange) out of Interzone.cpp, unchanged, and wraps them in
test/mock_rack.hpp plus a small C interface, so test/interzone_test.cc can run VCV's module and src/engine.cc side by
side on the same notes and compare their output. The panel widget and JSON code are left out (they need Rack's GUI).
"""
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
SRC = os.path.join(ROOT, "third_party", "valley", "src", "Interzone")


def main():
    out = sys.argv[1]
    hpp = open(os.path.join(SRC, "Interzone.hpp")).read()
    cpp = open(os.path.join(SRC, "Interzone.cpp")).read()
    m = re.search(r"struct Interzone : Module \{.*?\n\};\n", hpp, re.S)
    if not m:
        sys.exit("make_ref: struct Interzone not found in Interzone.hpp")
    module = m.group(0)
    start = cpp.index("Interzone::Interzone() {")
    end = cpp.index("json_t* Interzone::dataToJson()")
    funcs = cpp[start:end]
    includes = [l for l in hpp.splitlines() if l.startswith('#include "../dsp/')]
    includes = [l.replace('"../dsp/', '"dsp/') for l in includes]
    text = "\n".join([
        "// generated by test/make_ref.py from third_party/valley/src/Interzone: do not edit",
        '#include <stdlib.h>',
        '#include <string.h>',
        '#include <new>',
        '#include "mock_rack.hpp"',
    ] + includes + [
        "",
        module,
        funcs,
        "json_t* Interzone::dataToJson() { return NULL; }",
        "void Interzone::dataFromJson(json_t*) {}",
        "ref::App ref_app;",
        "ref::App* ref::APP = &ref_app;",
        "",
        'extern "C" {',
        "// zeroed memory, as the plugin's: the module leaves some members unset until its first getParams()",
        "void* ref_create() {",
        "  void* mem = NULL;",
        "  if (posix_memalign(&mem, 64, sizeof(Interzone)) != 0) return NULL;",
        "  memset(mem, 0, sizeof(Interzone));",
        "  return new (mem) Interzone();",
        "}",
        "void ref_destroy(void* m) { static_cast<Interzone*>(m)->~Interzone(); free(m); }",
        "void ref_param(void* m, int id, float v) { static_cast<Interzone*>(m)->params[id].setValue(v); }",
        "void ref_input(void* m, int id, int channels, const float* v) {",
        "  Interzone* z = static_cast<Interzone*>(m);",
        "  z->inputs[id].channels = channels;",
        "  for (int c = 0; c < 16; ++c) z->inputs[id].voltages[c] = c < channels ? v[c] : 0.f;",
        "}",
        "void ref_process(void* m) { Interzone::ProcessArgs a; static_cast<Interzone*>(m)->process(a); }",
        "float ref_output(void* m, int id, int c) { return static_cast<Interzone*>(m)->outputs[id].voltages[c]; }",
        "int ref_output_channels(void* m, int id) { return static_cast<Interzone*>(m)->outputs[id].channels; }",
        "}",
        "",
    ])
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w").write(text)


if __name__ == "__main__":
    main()
