#!/usr/bin/env python3
"""Write layout.conf (mpc-vst-plugins layout syntax) from tools/panel.py and the VOICE page below.

    python3 tools/layout.py --write    rewrite layout.conf
    python3 tools/layout.py --check    fail if layout.conf differs from what --write would make (build.sh, run_tests.sh)

The Interzone pages' controls are placed where tools/panel.py puts the module's widgets; the framework builds them
(sliders, knobs and toggles, so MPC binds, focuses and Q-Links them as usual) and tools/panel_art.py then gives each
its own artwork and exact bounds. The `w`/`h`/`r` given here only size the framework's placeholder images.
Q-Links follow tools/panel.py's QLINKS: the panel read left to right, a section at a time.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import panel  # noqa: E402

ROOT = panel.ROOT
LAYOUT = os.path.join(ROOT, "layout.conf")

HEADER = """# InterzoneXXL -- page layout (mpc-vst-plugins layout.conf syntax: tools/shadow_skin.py, docs/SKIN_STUDIO.md).
# GENERATED by tools/layout.py from tools/panel.py: edit those, then run `python3 tools/layout.py --write`.
# Coordinates are Force Shadow pixels: the plugin area is x 0..1280, y 86..714.
scale_names=1
label_scale=1.0
theme_bg=282828
theme_panel=282828
theme_line=ffffff
theme_ink=ffffff
theme_ink_dim=cfcfcf
theme_ink_faint=6a6a6a
theme_accent=f29a2e
theme_accent_hi=ffffff
theme_knob_face=1c1c1c
theme_knob_ring=f29a2e
theme_knob_dot=ffffff
theme_bar=282828
theme_seg_active=f29a2e
theme_seg_inactive=1c1c1c
theme_seg_active_tx=111111
theme_btn_text=ffffff
theme_tab_on=ffffff
theme_tab_on_tx=111111
theme_lcd=1c1c1c
theme_box=1c1c1c
"""

# VOICE: the MIDI voice and the output stage (not on the module). Section boxes and titles are drawn by
# tools/panel_art.py in the panel's style (VOICE_DECOR).
VOICE = """
[tab VOICE]
enum_h cx=175 cy=300 sw=150 sh=60 label="" key=voice_mode
knob cx=470 cy=300 r=44 label="POLY VOICES" key=voices
enum_h cx=175 cy=520 sw=150 sh=60 label="" key=mono_trig
knob cx=470 cy=520 r=44 label="BEND RANGE" key=bend
knob cx=755 cy=300 r=44 label="LEVEL" key=level
knob cx=920 cy=300 r=44 label="DRIVE" key=lim_drive
knob cx=1085 cy=300 r=44 label="CEILING" key=lim_ceiling
knob cx=755 cy=520 r=44 label="RELEASE" key=lim_release
button cx=1003 cy=520 label="PANIC" key=panic color=d23a2a
qlinks "VOICE" = voice_mode,voices,mono_trig,bend,level,lim_drive,lim_ceiling,lim_release,panic
"""
# (x, y, w, h, title) in Force coordinates, and text lines (cx, cy, size, text)
VOICE_DECOR = {
    "boxes": [(20, 160, 600, 540, "VOICE"), (640, 160, 620, 540, "OUTPUT")],
    "texts": [(175, 245, 22, "MODE"), (175, 465, 22, "MONO NOTES"), (1003, 580, 18, "all to default, all notes off"),
              (1260, 112, 26, "InterzoneXXL")],
}


def knob_r(box):
    return max(20, min(58, box[2] // 2 - 5))


def build():
    lines = [HEADER.rstrip("\n")]
    pl = panel.placements()
    for t, page in enumerate(panel.PAGES):
        tab = page["tab"]
        lines += ["", "[tab %s]" % tab]
        for c in [c for c in pl if c["tab"] == tab]:
            x, y, w, h = c["box"]
            cx, cy = x + w // 2, y + h // 2 + panel.Y_OFF
            if c["widget"] in ("slider", "step", "ckss3") or (c["widget"] == "knob" and is_option_knob(c)):
                lines.append('slider_v cx=%d cy=%d w=%d h=%d label="" key=%s ns=0 bw=%d'
                             % (cx, cy, w, h, c["key"], panel.value_width(c, pl)))
            elif c["widget"] == "knob":
                lines.append('knob cx=%d cy=%d r=%d label="" key=%s ns=0 bw=%d'
                             % (cx, cy, knob_r(c["box"]), c["key"], panel.value_width(c, pl)))
            else:
                lines.append('toggle cx=%d cy=%d label="" key=%s ns=0 bw=%d' % (cx, cy, c["key"], w))
        lines.append('qlinks "%s" = %s' % (tab, ",".join(panel.QLINKS[tab])))
    lines.append(VOICE.rstrip("\n"))
    lines.append("qlinks_track = " + ",".join(panel.QLINKS[panel.PAGES[0]["tab"]]))
    return "\n".join(lines) + "\n"


def is_option_knob(c):
    return c["widget"] == "knob" and c["art"][1] is not None


def check_qlinks():
    pl = panel.placements()
    for page in panel.PAGES:
        tab = page["tab"]
        keys = [c["key"] for c in pl if c["tab"] == tab]
        q = panel.QLINKS[tab]
        if sorted(keys) != sorted(q) or len(q) > 16:
            sys.exit("layout: page %s: the Q-Links (%s) must be every control on it once (%s), at most 16"
                     % (tab, ",".join(q), ",".join(keys)))


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "--check"
    check_qlinks()
    text = build()
    if mode == "--write":
        open(LAYOUT, "w").write(text)
        print("layout: layout.conf written")
        return
    have = open(LAYOUT).read() if os.path.exists(LAYOUT) else ""
    if have != text:
        sys.exit("layout: layout.conf is out of date: run tools/layout.py --write")
    print("layout: layout.conf up to date (%d pages)" % (len(panel.PAGES) + 1))


if __name__ == "__main__":
    main()
